### ISSUE TITLE
Playing order on lobby test

### ISSUE THREAD

**Issue by fishinsea2014** [159356-1702-Extramural/capstone#266] opened 2017-09-29 21:42 UTC
Do four times live test on the lobby.
The playing order is: 1-2-3, 3-1-2, 2-1-3, 1-3-2

**Comment by Luke-Nukem** [comment] 2017-09-29 21:59
Closing as this was just a misunderstanding. The order will vary for every *new game* started.

Not a bug.

**Closed by Luke-Nukem** 2017-09-29 21:59 UTC
